export interface RequestParameters {
  /**
   * Google Ad Manager ad unit code, including your Google Ad Manager network
   * code. To include multiple levels, use the slash (/) character as a
   * separator.
   *
   * Examples:
   *  - /1234/homepage
   *  - /5678/sports/baseball
   */
  iu: string;

  /**
   * Creative size. To include multiple sizes use the pipe (|) character as a
   * separator between them.
   *
   * Examples:
   *  - 320x50 for a single size
   *  - 320x50|300x50 for multiple sizes
   */
  sz: string;

  /**
   * Correlator (or, cache-busting) value. This must be a random number
   * (letters are not permitted) generated by a publisher to ensure a fresh
   * call to the ad server happens each time the page loads to avoid
   * impression-counting discrepancies.
   *
   * Example:
   *  - 8362527364
   */
  c: number;

  /**
   * Position of the tag on a webpage. The value should be a unique integer.
   * For an easier implementation, we recommend a value counting up.
   *
   * This is only required if multiple ad tags use the same ad unit code (iu=)
   * and correlator (c=) values on the same page.
   */
  tile: number;

  /**
   * Delayed impression toggle. If included, impression counting upon request
   * is disabled and either the viewed impression macro in the returned
   * creative or the information from the d_imp_hdr parameter is used to record
   * an impression.
   *
   * See: https://support.google.com/admanager/answer/2376981/macros
   * for more on viewed impression macros.
   *
   * 0 is the default value for Google Ad Manager impression counting.
   */
  d_imp?: 0 | 1;

  /**
   * Delayed impression header information toggle. If included, the view URL to
   * be used for impression counting is returned in the HTTP header. By default,
   * this header information is not defined. A publisher then needs to manually
   * ping this view URL to count an impression. Learn more about impression
   * counting and Tagless Requests.
   *
   * The Google-Delayed-Impression header contains the Google Ad Manager
   * impression URL.
   *
   * The Google-3rdParty-Delayed-Impression header contains the third-party
   * impression URL, if present in the creative.
   *
   * 0 explicitly disables delayed impression header information.
   */
  d_imp_hdr?: 0 | 1;

  /**
   * Slot-level key-value pairs.
   *
   * The following characters are not permitted in keys or values:
   * " ' ! + # * ~ ; ^ ( ) < > [ ] = .
   *
   * Spaces are allowed in values, but not in keys.
   */
  t?: Record<string, string | number>;

  /**
   * Mime-type value on the HTTP header.
   *
   * Example:
   *  - text/wml
   */
  m?: string;

  /**
   * Mobile ad request indicator.
   *
   * "js" is the only accepted value
   */
  mob?: "js";

  /**
   * Mobile device screen width, which overrides the automatic detection done
   * by the ad server.
   *
   * Example:
   *  - 1024
   */
  u_w?: number;

  /**
   * Mobile device screen height, which overrides the automatic detection done
   * by the ad server.
   *
   * Example:
   *  - 768
   */
  u_h?: number;

  /**
   * Mobile device hardware information, which overrides the automatic
   * detection done by the ad server.
   *
   * Examples:
   *  - iPhone8,1
   *  - iPad1,1
   */
  submodel?: string;
}
